### PR TITLE
add Dockerfile

### PR DESCRIPTION
**Pull request by Strubbl**
This PR adds a Dockerfile to make this app run in a container. At the moment this works and the app comes up. But it is stuck in the full screen loading screen, which cannot be cancelled.

Do you have any hint why this gets stuck in the following screen?

grafik

edit: also one could add an unprivileged user, so that this app does not run with root rights. But at first i would like to resolve the mentioned issue.

edit2:

```
docker build --pull -t strubbl_notesreview .
docker run -p 192.168.0.3:2999:5173 strubbl_notesreview
```
and browse to http://192.168.0.3:2999

### CODE REVIEW

**Comment by ENT8R** [comment]
It probably does not work because the is no file at `app/.env` which contains the necessary environment variables. This information was missing in the contributing guidelines as well, so I took the opportunity to fix this together with #110

Anyway, I do not see any real advantage of an additional Dockerfile at the moment except that only a single command is needed to start the application. Whereas with `npm run dev` actually only one command is needed as well...
Or did you maybe have any additional use cases in mind for which a Dockerfile is beneficial when you created this pull request?

**Comment by Strubbl** [comment]
Ok, fine for me. We can close the PR. Anyways I will keep the branch in my fork.

Thank you for the update of the contributing document. I'll take a look at it later.

The reason of docker for me is, that I do not want to install npm on my main machine. I like that it is only installed in a container, which i can shut down. Also this it does not interfere with other nodejs projects. So, the dev environment is the reproducible.

**Comment by ENT8R** [comment]
Ah, that seems like a useful addition then. If there is some way to add the necessary `.env` file before running `npm run dev` it would be cool if you could add it to this pull request, so I can merge it.

**Comment by Strubbl** [comment]
Thank you, now it works within the docker container.

I use the following commands to build and run: 
  ```
  docker build --pull -t strubbl_notesreview .
  docker run -p 192.168.0.3:2999:5173 strubbl_notesreview
  ```
and then i browse to http://192.168.0.3:2999

Of course you can adjust `192.168.0.3:2999` to match your needs.

Unfortunately, the container cannot be shutdown with CTRL+C, so i use `docker ps` to get the Docker ID of that container and `docker kill ID` to stop the container

**Pull request merged**
